// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepositoryLayer;

namespace RepositoryLayer.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.Models.Administrator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Administratori");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@admin.com",
                            Ime = "admin",
                            IsSuperAdmin = true,
                            Prezime = "admin"
                        });
                });

            modelBuilder.Entity("Model.Models.BannedKupac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumDo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Razlog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Zauvijek")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("BannedKupci");
                });

            modelBuilder.Entity("Model.Models.Grad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostanskiBroj")
                        .HasColumnType("int");

                    b.Property<int>("ZupanijaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZupanijaId");

                    b.ToTable("Gradovi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Citluk",
                            PostanskiBroj = 88260,
                            ZupanijaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "Siroki Brijeg",
                            PostanskiBroj = 88520,
                            ZupanijaId = 2
                        });
                });

            modelBuilder.Entity("Model.Models.Komentar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("KupacId")
                        .HasColumnType("int");

                    b.Property<int>("MobitelId")
                        .HasColumnType("int");

                    b.Property<string>("Sadrzaj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KupacId");

                    b.HasIndex("MobitelId");

                    b.ToTable("Komentari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Datum = new DateTime(2020, 9, 23, 4, 19, 35, 117, DateTimeKind.Local).AddTicks(9652),
                            IsDeleted = false,
                            KupacId = 1,
                            MobitelId = 1
                        });
                });

            modelBuilder.Entity("Model.Models.Kupac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BannedKupacId")
                        .HasColumnType("int");

                    b.Property<string>("BrojMobitela")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BrojPokusaja")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumPokusaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GradId")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BannedKupacId");

                    b.HasIndex("GradId");

                    b.ToTable("Kupci");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrojMobitela = "063525555",
                            BrojPokusaja = 0,
                            DatumPokusaja = new DateTime(2020, 9, 23, 4, 19, 35, 118, DateTimeKind.Local).AddTicks(3930),
                            Email = "kupac@kupac.com",
                            GradId = 1,
                            Ime = "kupac",
                            Prezime = "kupic"
                        });
                });

            modelBuilder.Entity("Model.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionDescriptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("Model.Models.Mobiteli", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cijena")
                        .HasColumnType("float");

                    b.Property<float>("DijagonalaEkrana")
                        .HasColumnType("real");

                    b.Property<bool>("EksternaMemorija")
                        .HasColumnType("bit");

                    b.Property<string>("Graficka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("KapacitetBaterije")
                        .HasColumnType("int");

                    b.Property<string>("KratkiOpis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Megapikseli")
                        .HasColumnType("real");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OperativniSustavId")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PopustId")
                        .HasColumnType("int");

                    b.Property<string>("Procesor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProdanoKomada")
                        .HasColumnType("int");

                    b.Property<int?>("ProizvodjacId")
                        .HasColumnType("int");

                    b.Property<float>("Ram_Gb")
                        .HasColumnType("real");

                    b.Property<string>("Rezolucija")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StanjeNaSkladistu")
                        .HasColumnType("int");

                    b.Property<int>("Tezina")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OperativniSustavId");

                    b.HasIndex("PopustId");

                    b.HasIndex("ProizvodjacId");

                    b.ToTable("Mobiteli");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cijena = 1210.0,
                            DijagonalaEkrana = 6.1f,
                            EksternaMemorija = true,
                            Graficka = "Ardent",
                            IsDeleted = false,
                            KapacitetBaterije = 3200,
                            KratkiOpis = "Lorem Ipsum je jednostavno probni tekst koji se koristi u tiskarskoj i slovoslagarskoj industriji. Lorem Ipsum postoji kao industrijski standard još od 16-og stoljeća",
                            Megapikseli = 12.3f,
                            Naziv = "S10",
                            OperativniSustavId = 1,
                            Opis = "Lorem Ipsum je jednostavno probni tekst koji se koristi u tiskarskoj i slovoslagarskoj industriji. Lorem Ipsum postoji kao industrijski standard još od 16-og stoljeća, kada je nepoznati tiskar uzeo tiskarsku galiju slova i posložio ih da bi napravio knjigu s uzorkom tiska. Taj je tekst ne samo preživio pet stoljeća, već se i vinuo u svijet elektronskog slovoslagarstva, ostajući u suštini nepromijenjen. Postao je popularan tijekom 1960-ih s pojavom Letraset listova s odlomcima Lorem Ipsum-a, a u skorije vrijeme sa software-om za stolno izdavaštvo kao što je Aldus PageMaker koji također sadrži varijante Lorem Ipsum-a.",
                            PopustId = 1,
                            Procesor = "Xenon A5G",
                            ProdanoKomada = 0,
                            ProizvodjacId = 1,
                            Ram_Gb = 8f,
                            Rezolucija = "FULL HD IPS",
                            StanjeNaSkladistu = 10,
                            Tezina = 320
                        },
                        new
                        {
                            Id = 2,
                            Cijena = 1580.0,
                            DijagonalaEkrana = 6.1f,
                            EksternaMemorija = true,
                            Graficka = "Ardent",
                            IsDeleted = false,
                            KapacitetBaterije = 3200,
                            KratkiOpis = "Lorem Ipsum je jednostavno probni tekst koji se koristi u tiskarskoj i slovoslagarskoj industriji. Lorem Ipsum postoji kao industrijski standard još od 16-og stoljeća",
                            Megapikseli = 12.3f,
                            Naziv = "S20",
                            OperativniSustavId = 1,
                            Opis = "Lorem Ipsum je jednostavno probni tekst koji se koristi u tiskarskoj i slovoslagarskoj industriji. Lorem Ipsum postoji kao industrijski standard još od 16-og stoljeća, kada je nepoznati tiskar uzeo tiskarsku galiju slova i posložio ih da bi napravio knjigu s uzorkom tiska. Taj je tekst ne samo preživio pet stoljeća, već se i vinuo u svijet elektronskog slovoslagarstva, ostajući u suštini nepromijenjen. Postao je popularan tijekom 1960-ih s pojavom Letraset listova s odlomcima Lorem Ipsum-a, a u skorije vrijeme sa software-om za stolno izdavaštvo kao što je Aldus PageMaker koji također sadrži varijante Lorem Ipsum-a.",
                            PopustId = 1,
                            Procesor = "Xenon A5G",
                            ProdanoKomada = 0,
                            ProizvodjacId = 1,
                            Ram_Gb = 8f,
                            Rezolucija = "FULL HD IPS",
                            StanjeNaSkladistu = 10,
                            Tezina = 320
                        },
                        new
                        {
                            Id = 3,
                            Cijena = 990.0,
                            DijagonalaEkrana = 6.1f,
                            EksternaMemorija = true,
                            Graficka = "Ardent",
                            IsDeleted = false,
                            KapacitetBaterije = 3200,
                            KratkiOpis = "Lorem Ipsum je jednostavno probni tekst koji se koristi u tiskarskoj i slovoslagarskoj industriji. Lorem Ipsum postoji kao industrijski standard još od 16-og stoljeća",
                            Megapikseli = 12.3f,
                            Naziv = "S10 Lite",
                            OperativniSustavId = 1,
                            Opis = "Lorem Ipsum je jednostavno probni tekst koji se koristi u tiskarskoj i slovoslagarskoj industriji. Lorem Ipsum postoji kao industrijski standard još od 16-og stoljeća, kada je nepoznati tiskar uzeo tiskarsku galiju slova i posložio ih da bi napravio knjigu s uzorkom tiska. Taj je tekst ne samo preživio pet stoljeća, već se i vinuo u svijet elektronskog slovoslagarstva, ostajući u suštini nepromijenjen. Postao je popularan tijekom 1960-ih s pojavom Letraset listova s odlomcima Lorem Ipsum-a, a u skorije vrijeme sa software-om za stolno izdavaštvo kao što je Aldus PageMaker koji također sadrži varijante Lorem Ipsum-a.",
                            PopustId = 1,
                            Procesor = "Xenon A5G",
                            ProdanoKomada = 0,
                            ProizvodjacId = 1,
                            Ram_Gb = 8f,
                            Rezolucija = "FULL HD IPS",
                            StanjeNaSkladistu = 10,
                            Tezina = 320
                        },
                        new
                        {
                            Id = 4,
                            Cijena = 440.0,
                            DijagonalaEkrana = 6.1f,
                            EksternaMemorija = true,
                            Graficka = "Ardent",
                            IsDeleted = false,
                            KapacitetBaterije = 3200,
                            KratkiOpis = "Lorem Ipsum je jednostavno probni tekst koji se koristi u tiskarskoj i slovoslagarskoj industriji. Lorem Ipsum postoji kao industrijski standard još od 16-og stoljeća",
                            Megapikseli = 12.3f,
                            Naziv = "Redmi Note 9",
                            OperativniSustavId = 1,
                            Opis = "Lorem Ipsum je jednostavno probni tekst koji se koristi u tiskarskoj i slovoslagarskoj industriji. Lorem Ipsum postoji kao industrijski standard još od 16-og stoljeća, kada je nepoznati tiskar uzeo tiskarsku galiju slova i posložio ih da bi napravio knjigu s uzorkom tiska. Taj je tekst ne samo preživio pet stoljeća, već se i vinuo u svijet elektronskog slovoslagarstva, ostajući u suštini nepromijenjen. Postao je popularan tijekom 1960-ih s pojavom Letraset listova s odlomcima Lorem Ipsum-a, a u skorije vrijeme sa software-om za stolno izdavaštvo kao što je Aldus PageMaker koji također sadrži varijante Lorem Ipsum-a.",
                            PopustId = 1,
                            Procesor = "Xenon A5G",
                            ProdanoKomada = 0,
                            ProizvodjacId = 4,
                            Ram_Gb = 8f,
                            Rezolucija = "FULL HD IPS",
                            StanjeNaSkladistu = 10,
                            Tezina = 320
                        },
                        new
                        {
                            Id = 5,
                            Cijena = 1320.0,
                            DijagonalaEkrana = 6.1f,
                            EksternaMemorija = true,
                            Graficka = "Ardent",
                            IsDeleted = false,
                            KapacitetBaterije = 3200,
                            KratkiOpis = "Lorem Ipsum je jednostavno probni tekst koji se koristi u tiskarskoj i slovoslagarskoj industriji. Lorem Ipsum postoji kao industrijski standard još od 16-og stoljeća",
                            Megapikseli = 12.3f,
                            Naziv = "Pixel 4",
                            OperativniSustavId = 1,
                            Opis = "Lorem Ipsum je jednostavno probni tekst koji se koristi u tiskarskoj i slovoslagarskoj industriji. Lorem Ipsum postoji kao industrijski standard još od 16-og stoljeća, kada je nepoznati tiskar uzeo tiskarsku galiju slova i posložio ih da bi napravio knjigu s uzorkom tiska. Taj je tekst ne samo preživio pet stoljeća, već se i vinuo u svijet elektronskog slovoslagarstva, ostajući u suštini nepromijenjen. Postao je popularan tijekom 1960-ih s pojavom Letraset listova s odlomcima Lorem Ipsum-a, a u skorije vrijeme sa software-om za stolno izdavaštvo kao što je Aldus PageMaker koji također sadrži varijante Lorem Ipsum-a.",
                            PopustId = 1,
                            Procesor = "Xenon A5G",
                            ProdanoKomada = 0,
                            ProizvodjacId = 6,
                            Ram_Gb = 8f,
                            Rezolucija = "FULL HD IPS",
                            StanjeNaSkladistu = 10,
                            Tezina = 320
                        },
                        new
                        {
                            Id = 6,
                            Cijena = 2350.0,
                            DijagonalaEkrana = 6.1f,
                            EksternaMemorija = true,
                            Graficka = "Ardent",
                            IsDeleted = false,
                            KapacitetBaterije = 3200,
                            KratkiOpis = "Lorem Ipsum je jednostavno probni tekst koji se koristi u tiskarskoj i slovoslagarskoj industriji. Lorem Ipsum postoji kao industrijski standard još od 16-og stoljeća",
                            Megapikseli = 12.3f,
                            Naziv = "iPhone 11 pro",
                            OperativniSustavId = 2,
                            Opis = "Lorem Ipsum je jednostavno probni tekst koji se koristi u tiskarskoj i slovoslagarskoj industriji. Lorem Ipsum postoji kao industrijski standard još od 16-og stoljeća, kada je nepoznati tiskar uzeo tiskarsku galiju slova i posložio ih da bi napravio knjigu s uzorkom tiska. Taj je tekst ne samo preživio pet stoljeća, već se i vinuo u svijet elektronskog slovoslagarstva, ostajući u suštini nepromijenjen. Postao je popularan tijekom 1960-ih s pojavom Letraset listova s odlomcima Lorem Ipsum-a, a u skorije vrijeme sa software-om za stolno izdavaštvo kao što je Aldus PageMaker koji također sadrži varijante Lorem Ipsum-a.",
                            PopustId = 1,
                            Procesor = "Xenon A5G",
                            ProdanoKomada = 0,
                            ProizvodjacId = 2,
                            Ram_Gb = 8f,
                            Rezolucija = "FULL HD IPS",
                            StanjeNaSkladistu = 10,
                            Tezina = 320
                        },
                        new
                        {
                            Id = 7,
                            Cijena = 1220.0,
                            DijagonalaEkrana = 6.1f,
                            EksternaMemorija = true,
                            Graficka = "Ardent",
                            IsDeleted = false,
                            KapacitetBaterije = 3200,
                            KratkiOpis = "Lorem Ipsum je jednostavno probni tekst koji se koristi u tiskarskoj i slovoslagarskoj industriji. Lorem Ipsum postoji kao industrijski standard još od 16-og stoljeća",
                            Megapikseli = 12.3f,
                            Naziv = "iPhone XR",
                            OperativniSustavId = 2,
                            Opis = "Lorem Ipsum je jednostavno probni tekst koji se koristi u tiskarskoj i slovoslagarskoj industriji. Lorem Ipsum postoji kao industrijski standard još od 16-og stoljeća, kada je nepoznati tiskar uzeo tiskarsku galiju slova i posložio ih da bi napravio knjigu s uzorkom tiska. Taj je tekst ne samo preživio pet stoljeća, već se i vinuo u svijet elektronskog slovoslagarstva, ostajući u suštini nepromijenjen. Postao je popularan tijekom 1960-ih s pojavom Letraset listova s odlomcima Lorem Ipsum-a, a u skorije vrijeme sa software-om za stolno izdavaštvo kao što je Aldus PageMaker koji također sadrži varijante Lorem Ipsum-a.",
                            Procesor = "Xenon A5G",
                            ProdanoKomada = 0,
                            ProizvodjacId = 2,
                            Ram_Gb = 8f,
                            Rezolucija = "FULL HD IPS",
                            StanjeNaSkladistu = 10,
                            Tezina = 320
                        },
                        new
                        {
                            Id = 8,
                            Cijena = 880.0,
                            DijagonalaEkrana = 6.1f,
                            EksternaMemorija = true,
                            Graficka = "Ardent",
                            IsDeleted = false,
                            KapacitetBaterije = 3200,
                            KratkiOpis = "Lorem Ipsum je jednostavno probni tekst koji se koristi u tiskarskoj i slovoslagarskoj industriji. Lorem Ipsum postoji kao industrijski standard još od 16-og stoljeća",
                            Megapikseli = 12.3f,
                            Naziv = "iPhone 8",
                            OperativniSustavId = 2,
                            Opis = "Lorem Ipsum je jednostavno probni tekst koji se koristi u tiskarskoj i slovoslagarskoj industriji. Lorem Ipsum postoji kao industrijski standard još od 16-og stoljeća, kada je nepoznati tiskar uzeo tiskarsku galiju slova i posložio ih da bi napravio knjigu s uzorkom tiska. Taj je tekst ne samo preživio pet stoljeća, već se i vinuo u svijet elektronskog slovoslagarstva, ostajući u suštini nepromijenjen. Postao je popularan tijekom 1960-ih s pojavom Letraset listova s odlomcima Lorem Ipsum-a, a u skorije vrijeme sa software-om za stolno izdavaštvo kao što je Aldus PageMaker koji također sadrži varijante Lorem Ipsum-a.",
                            Procesor = "Xenon A5G",
                            ProdanoKomada = 0,
                            ProizvodjacId = 2,
                            Ram_Gb = 8f,
                            Rezolucija = "FULL HD IPS",
                            StanjeNaSkladistu = 10,
                            Tezina = 320
                        },
                        new
                        {
                            Id = 9,
                            Cijena = 390.0,
                            DijagonalaEkrana = 6.1f,
                            EksternaMemorija = true,
                            Graficka = "Ardent",
                            IsDeleted = false,
                            KapacitetBaterije = 3200,
                            KratkiOpis = "Lorem Ipsum je jednostavno probni tekst koji se koristi u tiskarskoj i slovoslagarskoj industriji. Lorem Ipsum postoji kao industrijski standard još od 16-og stoljeća",
                            Megapikseli = 12.3f,
                            Naziv = "Honor 9",
                            OperativniSustavId = 1,
                            Opis = "Lorem Ipsum je jednostavno probni tekst koji se koristi u tiskarskoj i slovoslagarskoj industriji. Lorem Ipsum postoji kao industrijski standard još od 16-og stoljeća, kada je nepoznati tiskar uzeo tiskarsku galiju slova i posložio ih da bi napravio knjigu s uzorkom tiska. Taj je tekst ne samo preživio pet stoljeća, već se i vinuo u svijet elektronskog slovoslagarstva, ostajući u suštini nepromijenjen. Postao je popularan tijekom 1960-ih s pojavom Letraset listova s odlomcima Lorem Ipsum-a, a u skorije vrijeme sa software-om za stolno izdavaštvo kao što je Aldus PageMaker koji također sadrži varijante Lorem Ipsum-a.",
                            Procesor = "Xenon A5G",
                            ProdanoKomada = 0,
                            ProizvodjacId = 3,
                            Ram_Gb = 8f,
                            Rezolucija = "FULL HD IPS",
                            StanjeNaSkladistu = 10,
                            Tezina = 320
                        },
                        new
                        {
                            Id = 10,
                            Cijena = 990.0,
                            DijagonalaEkrana = 6.1f,
                            EksternaMemorija = true,
                            Graficka = "Ardent",
                            IsDeleted = false,
                            KapacitetBaterije = 3200,
                            KratkiOpis = "Lorem Ipsum je jednostavno probni tekst koji se koristi u tiskarskoj i slovoslagarskoj industriji. Lorem Ipsum postoji kao industrijski standard još od 16-og stoljeća",
                            Megapikseli = 12.3f,
                            Naziv = "Mate 30 Pro",
                            OperativniSustavId = 1,
                            Opis = "Lorem Ipsum je jednostavno probni tekst koji se koristi u tiskarskoj i slovoslagarskoj industriji. Lorem Ipsum postoji kao industrijski standard još od 16-og stoljeća, kada je nepoznati tiskar uzeo tiskarsku galiju slova i posložio ih da bi napravio knjigu s uzorkom tiska. Taj je tekst ne samo preživio pet stoljeća, već se i vinuo u svijet elektronskog slovoslagarstva, ostajući u suštini nepromijenjen. Postao je popularan tijekom 1960-ih s pojavom Letraset listova s odlomcima Lorem Ipsum-a, a u skorije vrijeme sa software-om za stolno izdavaštvo kao što je Aldus PageMaker koji također sadrži varijante Lorem Ipsum-a.",
                            Procesor = "Xenon A5G",
                            ProdanoKomada = 0,
                            ProizvodjacId = 3,
                            Ram_Gb = 8f,
                            Rezolucija = "FULL HD IPS",
                            StanjeNaSkladistu = 10,
                            Tezina = 320
                        },
                        new
                        {
                            Id = 11,
                            Cijena = 250.0,
                            DijagonalaEkrana = 6.1f,
                            EksternaMemorija = true,
                            Graficka = "Ardent",
                            IsDeleted = false,
                            KapacitetBaterije = 3200,
                            KratkiOpis = "Lorem Ipsum je jednostavno probni tekst koji se koristi u tiskarskoj i slovoslagarskoj industriji. Lorem Ipsum postoji kao industrijski standard još od 16-og stoljeća",
                            Megapikseli = 12.3f,
                            Naziv = "B26",
                            OperativniSustavId = 1,
                            Opis = "Lorem Ipsum je jednostavno probni tekst koji se koristi u tiskarskoj i slovoslagarskoj industriji. Lorem Ipsum postoji kao industrijski standard još od 16-og stoljeća, kada je nepoznati tiskar uzeo tiskarsku galiju slova i posložio ih da bi napravio knjigu s uzorkom tiska. Taj je tekst ne samo preživio pet stoljeća, već se i vinuo u svijet elektronskog slovoslagarstva, ostajući u suštini nepromijenjen. Postao je popularan tijekom 1960-ih s pojavom Letraset listova s odlomcima Lorem Ipsum-a, a u skorije vrijeme sa software-om za stolno izdavaštvo kao što je Aldus PageMaker koji također sadrži varijante Lorem Ipsum-a.",
                            Procesor = "Xenon A5G",
                            ProdanoKomada = 0,
                            ProizvodjacId = 7,
                            Ram_Gb = 8f,
                            Rezolucija = "FULL HD IPS",
                            StanjeNaSkladistu = 10,
                            Tezina = 320
                        },
                        new
                        {
                            Id = 12,
                            Cijena = 30.0,
                            DijagonalaEkrana = 6.1f,
                            EksternaMemorija = true,
                            Graficka = "Ardent",
                            IsDeleted = false,
                            KapacitetBaterije = 3200,
                            KratkiOpis = "Lorem Ipsum je jednostavno probni tekst koji se koristi u tiskarskoj i slovoslagarskoj industriji. Lorem Ipsum postoji kao industrijski standard još od 16-og stoljeća",
                            Megapikseli = 12.3f,
                            Naziv = "Classic c221",
                            OperativniSustavId = 1,
                            Opis = "Lorem Ipsum je jednostavno probni tekst koji se koristi u tiskarskoj i slovoslagarskoj industriji. Lorem Ipsum postoji kao industrijski standard još od 16-og stoljeća, kada je nepoznati tiskar uzeo tiskarsku galiju slova i posložio ih da bi napravio knjigu s uzorkom tiska. Taj je tekst ne samo preživio pet stoljeća, već se i vinuo u svijet elektronskog slovoslagarstva, ostajući u suštini nepromijenjen. Postao je popularan tijekom 1960-ih s pojavom Letraset listova s odlomcima Lorem Ipsum-a, a u skorije vrijeme sa software-om za stolno izdavaštvo kao što je Aldus PageMaker koji također sadrži varijante Lorem Ipsum-a.",
                            Procesor = "Xenon A5G",
                            ProdanoKomada = 0,
                            ProizvodjacId = 8,
                            Ram_Gb = 8f,
                            Rezolucija = "FULL HD IPS",
                            StanjeNaSkladistu = 10,
                            Tezina = 320
                        },
                        new
                        {
                            Id = 13,
                            Cijena = 430.0,
                            DijagonalaEkrana = 6.1f,
                            EksternaMemorija = true,
                            Graficka = "Ardent",
                            IsDeleted = false,
                            KapacitetBaterije = 3200,
                            KratkiOpis = "Lorem Ipsum je jednostavno probni tekst koji se koristi u tiskarskoj i slovoslagarskoj industriji. Lorem Ipsum postoji kao industrijski standard još od 16-og stoljeća",
                            Megapikseli = 12.3f,
                            Naziv = "42",
                            OperativniSustavId = 1,
                            Opis = "Lorem Ipsum je jednostavno probni tekst koji se koristi u tiskarskoj i slovoslagarskoj industriji. Lorem Ipsum postoji kao industrijski standard još od 16-og stoljeća, kada je nepoznati tiskar uzeo tiskarsku galiju slova i posložio ih da bi napravio knjigu s uzorkom tiska. Taj je tekst ne samo preživio pet stoljeća, već se i vinuo u svijet elektronskog slovoslagarstva, ostajući u suštini nepromijenjen. Postao je popularan tijekom 1960-ih s pojavom Letraset listova s odlomcima Lorem Ipsum-a, a u skorije vrijeme sa software-om za stolno izdavaštvo kao što je Aldus PageMaker koji također sadrži varijante Lorem Ipsum-a.",
                            Procesor = "Xenon A5G",
                            ProdanoKomada = 0,
                            ProizvodjacId = 5,
                            Ram_Gb = 8f,
                            Rezolucija = "FULL HD IPS",
                            StanjeNaSkladistu = 10,
                            Tezina = 320
                        },
                        new
                        {
                            Id = 14,
                            Cijena = 430.0,
                            DijagonalaEkrana = 6.1f,
                            EksternaMemorija = true,
                            Graficka = "Ardent",
                            IsDeleted = false,
                            KapacitetBaterije = 3200,
                            KratkiOpis = "Lorem Ipsum je jednostavno probni tekst koji se koristi u tiskarskoj i slovoslagarskoj industriji. Lorem Ipsum postoji kao industrijski standard još od 16-og stoljeća",
                            Megapikseli = 12.3f,
                            Naziv = "210",
                            OperativniSustavId = 1,
                            Opis = "Lorem Ipsum je jednostavno probni tekst koji se koristi u tiskarskoj i slovoslagarskoj industriji. Lorem Ipsum postoji kao industrijski standard još od 16-og stoljeća, kada je nepoznati tiskar uzeo tiskarsku galiju slova i posložio ih da bi napravio knjigu s uzorkom tiska. Taj je tekst ne samo preživio pet stoljeća, već se i vinuo u svijet elektronskog slovoslagarstva, ostajući u suštini nepromijenjen. Postao je popularan tijekom 1960-ih s pojavom Letraset listova s odlomcima Lorem Ipsum-a, a u skorije vrijeme sa software-om za stolno izdavaštvo kao što je Aldus PageMaker koji također sadrži varijante Lorem Ipsum-a.",
                            Procesor = "Xenon A5G",
                            ProdanoKomada = 0,
                            ProizvodjacId = 5,
                            Ram_Gb = 8f,
                            Rezolucija = "FULL HD IPS",
                            StanjeNaSkladistu = 10,
                            Tezina = 320
                        },
                        new
                        {
                            Id = 15,
                            Cijena = 670.0,
                            DijagonalaEkrana = 6.1f,
                            EksternaMemorija = true,
                            Graficka = "Ardent",
                            IsDeleted = false,
                            KapacitetBaterije = 3200,
                            KratkiOpis = "Lorem Ipsum je jednostavno probni tekst koji se koristi u tiskarskoj i slovoslagarskoj industriji. Lorem Ipsum postoji kao industrijski standard još od 16-og stoljeća",
                            Megapikseli = 12.3f,
                            Naziv = "A71",
                            OperativniSustavId = 1,
                            Opis = "Lorem Ipsum je jednostavno probni tekst koji se koristi u tiskarskoj i slovoslagarskoj industriji. Lorem Ipsum postoji kao industrijski standard još od 16-og stoljeća, kada je nepoznati tiskar uzeo tiskarsku galiju slova i posložio ih da bi napravio knjigu s uzorkom tiska. Taj je tekst ne samo preživio pet stoljeća, već se i vinuo u svijet elektronskog slovoslagarstva, ostajući u suštini nepromijenjen. Postao je popularan tijekom 1960-ih s pojavom Letraset listova s odlomcima Lorem Ipsum-a, a u skorije vrijeme sa software-om za stolno izdavaštvo kao što je Aldus PageMaker koji također sadrži varijante Lorem Ipsum-a.",
                            PopustId = 1,
                            Procesor = "Xenon A5G",
                            ProdanoKomada = 0,
                            ProizvodjacId = 1,
                            Ram_Gb = 8f,
                            Rezolucija = "FULL HD IPS",
                            StanjeNaSkladistu = 10,
                            Tezina = 320
                        });
                });

            modelBuilder.Entity("Model.Models.Narudzba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GradId")
                        .HasColumnType("int");

                    b.Property<string>("Kanton")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KontaktTelefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KupacId")
                        .HasColumnType("int");

                    b.Property<string>("Opcina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostanskiBroj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stanje")
                        .HasColumnType("int");

                    b.Property<double>("UkupnaCijena")
                        .HasColumnType("float");

                    b.Property<string>("Ulica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZaposlenikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GradId");

                    b.HasIndex("KupacId");

                    b.ToTable("Narudzbe");
                });

            modelBuilder.Entity("Model.Models.OperativniSustav", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Verzija")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("OperativniSustavi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Android",
                            Verzija = 11f
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "iOS",
                            Verzija = 13.4f
                        });
                });

            modelBuilder.Entity("Model.Models.Popusti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumDo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumOd")
                        .HasColumnType("datetime2");

                    b.Property<float>("PostotakPopusta")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Popusti");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DatumDo = new DateTime(2020, 9, 23, 4, 19, 35, 116, DateTimeKind.Local).AddTicks(9684),
                            DatumOd = new DateTime(2020, 9, 23, 4, 19, 35, 114, DateTimeKind.Local).AddTicks(4229),
                            PostotakPopusta = 0.1f
                        });
                });

            modelBuilder.Entity("Model.Models.Proizvodjac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Proizvodjaci");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Samsung"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "Apple"
                        },
                        new
                        {
                            Id = 3,
                            Naziv = "Huawei"
                        },
                        new
                        {
                            Id = 4,
                            Naziv = "Xiaomi"
                        },
                        new
                        {
                            Id = 5,
                            Naziv = "Nokia"
                        },
                        new
                        {
                            Id = 6,
                            Naziv = "Google"
                        },
                        new
                        {
                            Id = 7,
                            Naziv = "CAT"
                        },
                        new
                        {
                            Id = 8,
                            Naziv = "YEZZ"
                        });
                });

            modelBuilder.Entity("Model.Models.Slika", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MobitelId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<byte[]>("SlikaFull")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("SlikaThumb")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("MobitelId");

                    b.ToTable("Slike");
                });

            modelBuilder.Entity("Model.Models.SmsLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Broj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dodatnisadrzaj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poruka")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SmsLog");
                });

            modelBuilder.Entity("Model.Models.StavkaNarudzbe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cijena")
                        .HasColumnType("float");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int>("MobitelId")
                        .HasColumnType("int");

                    b.Property<int>("NarudzbaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MobitelId");

                    b.HasIndex("NarudzbaId");

                    b.ToTable("StavkeNarudzbe");
                });

            modelBuilder.Entity("Model.Models.Zupanija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zupanije");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Hercegovacko-Neretvanska"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "Zapadno-Hercegovacka"
                        });
                });

            modelBuilder.Entity("Model.Models.Grad", b =>
                {
                    b.HasOne("Model.Models.Zupanija", "Zupanija")
                        .WithMany("Grad")
                        .HasForeignKey("ZupanijaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Models.Komentar", b =>
                {
                    b.HasOne("Model.Models.Kupac", "Kupac")
                        .WithMany("Komentar")
                        .HasForeignKey("KupacId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Models.Mobiteli", "Mobitel")
                        .WithMany("Komentar")
                        .HasForeignKey("MobitelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Models.Kupac", b =>
                {
                    b.HasOne("Model.Models.BannedKupac", "BannedKupac")
                        .WithMany("Kupac")
                        .HasForeignKey("BannedKupacId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Model.Models.Grad", "Grad")
                        .WithMany("Kupac")
                        .HasForeignKey("GradId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Models.Mobiteli", b =>
                {
                    b.HasOne("Model.Models.OperativniSustav", "OperativniSustav")
                        .WithMany("Mobiteli")
                        .HasForeignKey("OperativniSustavId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Model.Models.Popusti", "Popust")
                        .WithMany()
                        .HasForeignKey("PopustId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Model.Models.Proizvodjac", "Prozivodjac")
                        .WithMany("Mobiteli")
                        .HasForeignKey("ProizvodjacId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Model.Models.Narudzba", b =>
                {
                    b.HasOne("Model.Models.Grad", null)
                        .WithMany("Narudzba")
                        .HasForeignKey("GradId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Model.Models.Kupac", "Kupac")
                        .WithMany("Narudzba")
                        .HasForeignKey("KupacId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Models.Slika", b =>
                {
                    b.HasOne("Model.Models.Mobiteli", "Mobitel")
                        .WithMany("Slika")
                        .HasForeignKey("MobitelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Models.StavkaNarudzbe", b =>
                {
                    b.HasOne("Model.Models.Mobiteli", "Mobitel")
                        .WithMany("StavkaNarudzbe")
                        .HasForeignKey("MobitelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Models.Narudzba", "Narudzba")
                        .WithMany("StavkaNarudzbe")
                        .HasForeignKey("NarudzbaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
